/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itja211_cgmsxbyz5_2;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Makro Centurion
 */
public class ENSCustomerProgram extends javax.swing.JFrame {

    /**
     * Creates new form ENSCustomerProgram
     */
    public ENSCustomerProgram() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("john.jpg")));
        
        ImageIcon menzi = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("john.jpg")));
        Image img1 = menzi.getImage();
        Image img2 = img1.getScaledInstance(picLabel.getWidth(), picLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        
        picLabel.setIcon(i);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whitePanel = new javax.swing.JPanel();
        picturePanel = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        custNameField = new javax.swing.JTextField();
        customerSurname = new javax.swing.JLabel();
        custSurnameField = new javax.swing.JTextField();
        custTelNum = new javax.swing.JLabel();
        custTelNumField = new javax.swing.JTextField();
        custAddress = new javax.swing.JLabel();
        custAddressField = new javax.swing.JTextField();
        searchForRecords = new javax.swing.JButton();
        updateRecords = new javax.swing.JButton();
        addRecord = new javax.swing.JButton();
        bluePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENS Customer Program");
        setLocationByPlatform(true);
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));

        picturePanel.setToolTipText("");
        picturePanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        customerName.setText("Customer Name:");

        custNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameFieldActionPerformed(evt);
            }
        });

        customerSurname.setText("Customer Surname:");

        custTelNum.setText("Customer telephone number:");

        custTelNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custTelNumFieldActionPerformed(evt);
            }
        });

        custAddress.setText("Customer Address:");

        searchForRecords.setText("Search for Record");
        searchForRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForRecordsActionPerformed(evt);
            }
        });

        updateRecords.setText("Update the records");
        updateRecords.setActionCommand("");
        updateRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordsActionPerformed(evt);
            }
        });

        addRecord.setText("Add Record");
        addRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout whitePanelLayout = new javax.swing.GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custNameField)
                    .addComponent(customerSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custSurnameField)
                    .addComponent(custTelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custTelNumField)
                    .addComponent(custAddressField)
                    .addGroup(whitePanelLayout.createSequentialGroup()
                        .addComponent(addRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchForRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(whitePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custTelNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custTelNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchForRecords)
                    .addComponent(addRecord))
                .addGap(18, 18, 18)
                .addComponent(updateRecords)
                .addGap(18, 18, 18)
                .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(whitePanel);

        bluePanel.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        getContentPane().add(bluePanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameFieldActionPerformed

    private void custTelNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custTelNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custTelNumFieldActionPerformed

    private void updateRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordsActionPerformed
        PreparedStatement ps;

        SQLStuff db = new SQLStuff();
        Connection con;
        
        try {
            
            con = (Connection) db.getConnection();
            
            String query = "UPDATE customer SET custSurname = ?, custNum = ?, custAddress = ? WHERE custName = ?";
       
            ps = (PreparedStatement) con.prepareStatement(query);
            
            String name = custNameField.getText();
            String surname = custSurnameField.getText();
            String telNum = custTelNumField.getText();
            String address = custAddressField.getText();
        
            ps.setString(1, name);
            ps.setString(2, surname);
            ps.setString(3, telNum);
            ps.setString(4, address);
            
            
            ps.execute();
            JOptionPane.showMessageDialog(null,"The Record was successfully updated.", "Record Successfully Updated", 2);
             
            con.close();
            
            
        } catch (SQLException sqle) {
            System.out.println("Error " + sqle);
            
        } catch (ClassNotFoundException cnfe){
            System.out.println("Error " + cnfe);
        } catch (Exception ex) {
            Logger.getLogger(ENSCustomerProgram.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateRecordsActionPerformed

    private void addRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordActionPerformed
        PreparedStatement ps;

        SQLStuff db = new SQLStuff();
        Connection con;
        
        try {
            
            con = (Connection) db.getConnection();
            
            String query = "INSERT INTO customer (custName, custSurname, custNum, custAddress)" + " VALUES (?, ?, ?, ?)";
       
            ps = (PreparedStatement) con.prepareStatement(query);
            
            String name = custNameField.getText();
            String surname = custSurnameField.getText();
            String telNum = custTelNumField.getText();
            String address = custAddressField.getText();
        
            
            ps.setString(1, name);
            ps.setString(2, surname);
            ps.setString(3, telNum);
            ps.setString(4, address);
            
            ps.execute();
            JOptionPane.showMessageDialog(null,"The Record was successfully inserted.", "Record Successfully Inserted", 2);
            
            con.close();
            
        } catch (SQLException sqle) {
            System.out.println("Error " + sqle);
            
        } catch (ClassNotFoundException cnfe){
            System.out.println("Error " + cnfe);
        } catch (Exception ex) {
            Logger.getLogger(ENSCustomerProgram.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addRecordActionPerformed

    private void searchForRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForRecordsActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        
        SQLStuff db = new SQLStuff();
        Connection con;
        
        try {
            
            con = (Connection) db.getConnection();
            
            String query = "SELECT * FROM customer WHERE custName=? AND custSurname=?";
            ps = (PreparedStatement) con.prepareStatement(query);
            
            String name = custNameField.getText();
            String surname = custSurnameField.getText();

            ps.setString(1, name);
            ps.setString(2, surname);
           
            ps.execute();
            
            rs = ps.executeQuery();
        
            if (rs.next()) {
         
            custTelNumField.setText(rs.getString("custNum"));
            custAddressField.setText(rs.getString("custAddress"));  
            
            JOptionPane.showMessageDialog(null,"Update the required records and click on the update records button if necessary.", "Search for Record", 2);
            
            }else{
                JOptionPane.showMessageDialog(null,"Something went wrong", "Error of sorts", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
        } catch (SQLException sqle) {
            System.out.println("Error " + sqle);
            
        } catch (ClassNotFoundException cnfe){
            System.out.println("Error " + cnfe);
        } catch (Exception ex) {
            Logger.getLogger(ENSCustomerProgram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchForRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ENSCustomerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ENSCustomerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ENSCustomerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ENSCustomerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ENSCustomerProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecord;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JLabel custAddress;
    private javax.swing.JTextField custAddressField;
    private javax.swing.JTextField custNameField;
    private javax.swing.JTextField custSurnameField;
    private javax.swing.JLabel custTelNum;
    private javax.swing.JTextField custTelNumField;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerSurname;
    private javax.swing.JLabel picLabel;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JButton searchForRecords;
    private javax.swing.JButton updateRecords;
    private javax.swing.JPanel whitePanel;
    // End of variables declaration//GEN-END:variables
}
